/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:033792d307ad2716c6dd4c484b48bdd8:14d9878f1049f243e176bc72993acc97:7160f28bb0548a348c1851e68e3b7ab7$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class 
	{
		public const string Organizem_0000s_0000_spike_backone = "organizem_0000s_0000_spike_backone";
		public const string Organizem_0002s_0002_food = "organizem_0002s_0002_food";
		public const string Organizem_0002s_0001_speed = "organizem_0002s_0001_speed";
		public const string Organizem_0002s_0000_size = "organizem_0002s_0000_size";
		public const string Organizem_0004s_0003_ustaL = "organizem_0004s_0003_ustaL";
		public const string Organizem_0004s_0004_ustaD = "organizem_0004s_0004_ustaD";
		public const string Organizem_0004s_0000_usta3 = "organizem_0004s_0000_usta3";
		public const string Organizem_0004s_0001_ustaL2 = "organizem_0004s_0001_ustaL2";
		public const string Organizem_0004s_0002_ustaD2 = "organizem_0004s_0002_ustaD2";
		public const string Organizem_0003s_0000_ucki_not3 = "organizem_0003s_0000_ucki_not3";
		public const string Organizem_0003s_0002_ucki_not1 = "organizem_0003s_0002_ucki_not1";
		public const string Organizem_0003s_0001_ucki_not2 = "organizem_0003s_0001_ucki_not2";
		public const string Organizem_0003s_0003_ucki_zun = "organizem_0003s_0003_ucki_zun";
		public const string Organizem_0001s_0000_e9 = "organizem_0001s_0000_e9";
		public const string Organizem_0001s_0001_e8 = "organizem_0001s_0001_e8";
		public const string Organizem_0001s_0002_e7 = "organizem_0001s_0002_e7";
		public const string Organizem_0001s_0003_e6 = "organizem_0001s_0003_e6";
		public const string Organizem_0001s_0004_e5 = "organizem_0001s_0004_e5";
		public const string Organizem_0001s_0005_e4 = "organizem_0001s_0005_e4";
		public const string Organizem_0001s_0006_e3 = "organizem_0001s_0006_e3";
		public const string Organizem_0001s_0007_e2 = "organizem_0001s_0007_e2";
		public const string Organizem_0001s_0008_e1 = "organizem_0001s_0008_e1";
		public const string Organizem_0000s_0001_spike_sides = "organizem_0000s_0001_spike_sides";
		public const string Organizem_0000s_0002_spike_back = "organizem_0000s_0002_spike_back";
		public const string Organizem_0000s_0003_spike_front = "organizem_0000s_0003_spike_front";
		public const string Organizem_0000_base4 = "organizem_0000_base4";
		public const string Organizem_0003_base1 = "organizem_0003_base1";
		public const string Organizem_0001_base3 = "organizem_0001_base3";
		public const string Organizem_0002_base2 = "organizem_0002_base2";
	}
}